CREATE TABLE USERS (
    USERID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLE VARCHAR2(255) DEFAULT 'user',
    FULLNAME VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    PHONE_NUMBER CHAR(11) NOT NULL,
    ADDRESS VARCHAR2(255) NOT NULL
);

SELECT
    *
FROM
    USERS;

CREATE TABLE RESTAURANTS (
    RESTAURANTID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMAIL VARCHAR2(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    RESTAURANTNAME VARCHAR2(255) NOT NULL,
    ADDRESS VARCHAR2(255) NOT NULL,
    PHONE_NUMBER CHAR(11) NOT NULL,
    WEBSITE VARCHAR2(255) NOT NULL
);

CREATE TABLE RESTAURANTITEMS(
    PRODUCTID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RESTAURANTID NUMBER NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    DESCRIPTION VARCHAR2(255) NOT NULL,
    CATEGORY VARCHAR2(255) NOT NULL,
    PRICE NUMBER NOT NULL,
    FOREIGN KEY (RESTAURANTID) REFERENCES RESTAURANTS(RESTAURANTID)
);

CREATE TABLE ORDERS(
    ORDERID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERID NUMBER NOT NULL,
    RESTAURANTID NUMBER NOT NULL,
    ORDERTIMEDATE TIMESTAMP NOT NULL,
    ORDERSTATUS VARCHAR2(255) NOT NULL,
    GRANDTOTAL NUMBER(7, 2),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID),
    FOREIGN KEY (RESTAURANTID) REFERENCES RESTAURANTS(RESTAURANTID)
);

CREATE TABLE ORDER_DETAILS(
    ORDERID NUMBER NOT NULL,
    PRODUCTID NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    SUBTOTAL NUMBER(7, 2) NOT NULL,
    FOREIGN KEY (ORDERID) REFERENCES ORDERS(ORDERID),
    FOREIGN KEY (PRODUCTID) REFERENCES RESTAURANTITEMS(PRODUCTID),
    PRIMARY KEY (ORDERID, PRODUCTID)
);